url    : "http://127.0.0.1:4000"
baseurl: ""

title      : Intellify
email      : support@intellify.co.za
description: "Go online, grow online."
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

logo:
  path: /assets/img/logo/intellify-logo-white.png